image: alpine

variables:
  SBT_VERSION: "1.2.8"
  SBT_OPTS: "-Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=2G -Xss2M  -Duser.timezone=GMT -Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
  COURSIER_CACHE: sbt-cache/coursier

stages:
  - censor # first censor cause it's faster
  - test
  - integration
  - deploy
  

cache:
  key: "mycachekey"
  paths:
    - "sbt-cache/ivy/cache"
    - "sbt-cache/boot"
    - "sbt-cache/sbtboot"
    - "sbt-cache/target"
    - "sbt-cache/coursier"

test:
  stage: test
  interruptible: true
  image: "hseeberger/scala-sbt:8u181_2.12.8_1.2.8"
  script:
    - sbt clean coverageOn test coverageOff coverageReport coverageAggregate
  only:
    - /^develop$/
    - /(^release\/v([0-9]+)\.([0-9]+))/
    - merge_requests

censor:
  stage: censor
  interruptible: true
  image: "registry.gitlab.com/agilefactory/developers/censor:0.1.0-SNAPSHOT"
  only: [merge_requests]
  script:
    - bash censor.sh
    

integration:
  tags:
    - cluster01
  interruptible: true
  stage: integration
  image: "hseeberger/scala-sbt:8u181_2.12.8_1.2.8"
  script:
    - sbt clean it:test
  only:
    - /(^release\/v([0-9]+)\.([0-9]+))/

deploy:
  interruptible: false
  tags:
    - cluster01
  stage: deploy
  image: "hseeberger/scala-sbt:8u181_2.12.8_1.2.8"
  script:
    - sbt clean publish
  only:
    - /^develop$/
    - /(^release\/v([0-9]+)\.([0-9]+))/
    - merge_requests
