version: '2'
services:
 hbase:
      build: ./hbase
      image: hbase_cdh:5.12
      hostname: hbase
      ports:
          - "60010:60010"
      mem_limit: 800m

networks:
  default:
    external:
      name: wasp-docker
